// Code generated by gonstructor -type=NpcGenerator -constructorTypes=builder -init=init -propagateInitFuncReturns -output=npc_generator_auto.go; DO NOT EDIT.

package generator

type NpcGeneratorBuilder struct {
	nameGenerator NameGenerator
}

func NewNpcGeneratorBuilder() *NpcGeneratorBuilder {
	return &NpcGeneratorBuilder{}
}

func (b *NpcGeneratorBuilder) NameGenerator(nameGenerator NameGenerator) *NpcGeneratorBuilder {
	b.nameGenerator = nameGenerator
	return b
}

func (b *NpcGeneratorBuilder) Build() (*NpcGenerator, error) {
	r := &NpcGenerator{
		nameGenerator: b.nameGenerator,
	}
	ret_init0 := r.init()
	return r, ret_init0
}
