// Code generated by gonstructor -type=NpcGenerator -constructorTypes=builder -init=init -propagateInitFuncReturns -output=npc_generator_auto.go; DO NOT EDIT.

package generator

type NpcGeneratorBuilder struct {
	generateName GenerateName
}

func NewNpcGeneratorBuilder() *NpcGeneratorBuilder {
	return &NpcGeneratorBuilder{}
}

func (b *NpcGeneratorBuilder) GenerateName(generateName GenerateName) *NpcGeneratorBuilder {
	b.generateName = generateName
	return b
}

func (b *NpcGeneratorBuilder) Build() (*NpcGenerator, error) {
	r := &NpcGenerator{
		generateName: b.generateName,
	}
	ret_init0 := r.init()
	return r, ret_init0
}
