name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Get version from CHANGELOG
        id: changelog
        run: |
          VERSION=$(grep -m1 -oP '(?<=## )[^ ]+' CHANGELOG.md)
          echo "::set-output name=version::$VERSION"
          echo "Version: $VERSION"

      - name: Create Tag
        run: |
          git tag ${{ steps.changelog.outputs.version }}
          git push origin ${{ steps.changelog.outputs.version }}