---
# This workflow validates that change log has a valid format

name: Validate Changelog

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate CHANGELOG format
        run: |
          if ! grep -qE '^## \[[0-9]+\.[0-9]+\.[0-9]+\] - [0-9]{4}-[0-9]{2}-[0-9]{2}' CHANGELOG.md; then
            echo "CHANGELOG format is incorrect, versions should be in the format ## X.Y.Z"
            exit 1
          fi
